/**
 * Extracts the Arabic + Latin woff2 subsets we need from the vendored
 * fontsource packages and writes a self-hosted fonts.css.
 * Run once:  node tools/build-fonts.js   (then the tmp_* folders can be deleted)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'fonts');
const WEIGHTS = ['400', '500', '600', '700'];
const SUBSETS = ['arabic', 'latin'];

const PACKAGES = [
  { tmp: 'tmp_cairo', family: 'Cairo' },
  { tmp: 'tmp_ibm-plex-sans-arabic', family: 'IBM Plex Sans Arabic' },
];

fs.mkdirSync(OUT, { recursive: true });

let css = `/* Self-hosted fonts — generated by tools/build-fonts.js.
   No network required: every file lives next to this stylesheet. */\n`;

for (const { tmp, family } of PACKAGES) {
  const pkgDir = path.join(ROOT, tmp, 'package');
  // fontsource ships one file per weight; index.css only carries weight 400.
  const index = WEIGHTS
    .map((w) => fs.readFileSync(path.join(pkgDir, `${w}.css`), 'utf8'))
    .join('\n');

  // Split the fontsource index.css into individual @font-face blocks.
  const blocks = index.match(/@font-face\s*\{[^}]*\}/g) || [];

  for (const block of blocks) {
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const file = (block.match(/url\(\.\/files\/([^)]+)\)/) || [])[1];
    if (!weight || !file) continue;
    if (!WEIGHTS.includes(weight)) continue;
    // filename shape: <family>-<subset>-<weight>-normal.woff2
    // the family itself may contain dashes, so anchor on the subset token
    const subset = (file.match(/(?:^|-)(arabic|latin)-\d+-normal\.woff2$/) || [])[1];
    if (!subset) continue;

    fs.copyFileSync(path.join(pkgDir, 'files', file), path.join(OUT, file));

    // fontsource points at ./files/ and ships a .woff fallback; we only keep
    // the woff2 and flatten it next to fonts.css
    let flat = block.replace(/url\(\.\/files\/([^)]+?)\.woff2\)\s*format\('woff2'\)\s*,\s*url\(\.\/files\/[^)]+?\.woff\)\s*format\('woff'\)/,
      (_, name) => `url(./${name}.woff2) format('woff2')`);
    flat = flat.replace(/url\(\.\/files\//g, 'url(./');

    css += flat.replace(/\n\s+/g, '\n  ').trim() + '\n';
  }
}

fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
const count = fs.readdirSync(OUT).filter((f) => f.endsWith('.woff2')).length;
console.log(`fonts: ${count} woff2 files, fonts.css ${css.length} bytes`);
